version: '3'

services:
  bwapp:
    build: .
    container_name: bwapp
    ports:
      - "8082:80"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=bug
      - MYSQL_DATABASE=bwapp
      - MYSQL_USER=bee
      - MYSQL_PASSWORD=bug
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: bwapp-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=bug
      - MYSQL_DATABASE=bwapp
      - MYSQL_USER=bee
      - MYSQL_PASSWORD=bug
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
